spring.application.name=A3_DE180895_SE18D04

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=A3_DE180895_SE18D04;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8
spring.datasource.username=nguyentoan
spring.datasource.password=congtoan0101
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# ============================================
# JPA / HIBERNATE CONFIGURATION
# ============================================
# Validate schema (không t? ??ng t?o/s?a b?ng vì ?ã t?o th? công)
spring.jpa.hibernate.ddl-auto=update
# Hi?n th? SQL queries trong console (t?t trong production)
#spring.jpa.show-sql=true
# Format SQL queries cho d? ??c
spring.jpa.properties.hibernate.format_sql=true
# Dialect cho SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt.secret=6I5yybOm3P0UPQOXmR1XhqmoFJducAYa5vt75VaIn8Q=
jwt.expiration=3600000
